import { routeGroups } from './route-groups'

export const basicRoutes = [
  {
    name: 'Login',
    path: '/login',
    component: () => import('@/views/login/index.vue'),
    meta: {
      titleKey: 'menu.login',
      layout: 'empty',
      show: false,
    },
  },
  {
    name: 'Root',
    path: '/',
    component: () => import('@/views/redirect/index.vue'),
    meta: {
      layout: 'empty',
      show: false,
    },
  },
  {
    name: 'Kyc',
    path: '/kyc',
    redirect: '/kyc/pending',
    meta: {
      titleKey: 'menu.Kyc',
      layout: 'normal',
      icon: 'i-fe:shield',
      order: 1,
      show: true,
      roles: ['ADMIN', 'AUDITOR'],
    },
  },
  {
    name: 'KycPending',
    path: '/kyc/pending',
    component: () => import('@/views/kyc/pending/index.vue'),
    meta: {
      titleKey: 'menu.KycPending',
      layout: 'normal',
      keepAlive: true,
      order: 1,
      show: true,
      roles: ['ADMIN', 'AUDITOR'],
      parentKey: 'Kyc',
    },
  },
  {
    name: 'KycAppeals',
    path: '/kyc/appeals',
    component: () => import('@/views/kyc/appeals/index.vue'),
    meta: {
      titleKey: 'menu.KycAppeals',
      layout: 'normal',
      keepAlive: true,
      order: 2,
      show: true,
      roles: ['ADMIN', 'AUDITOR'],
      parentKey: 'Kyc',
    },
  },
  {
    name: 'KycDetail',
    path: '/kyc/detail/:id',
    component: () => import('@/views/kyc/detail/index.vue'),
    meta: {
      titleKey: 'menu.KycDetail',
      layout: 'normal',
      keepAlive: false,
      order: 3,
      show: false,
      roles: ['ADMIN', 'AUDITOR'],
      parentKey: 'Kyc',
    },
  },
  {
    name: 'TicketList',
    path: '/tickets',
    component: () => import('@/views/tickets/index.vue'),
    meta: {
      titleKey: 'menu.TicketList',
      layout: 'normal',
      keepAlive: true,
      order: 1,
      show: true,
      roles: ['ADMIN', 'SUPPORT'],
      parentKey: 'Tickets',
      group: routeGroups.Tickets,
    },
  },
  {
    name: 'TicketDetail',
    path: '/tickets/:id',
    component: () => import('@/views/tickets/detail/index.vue'),
    meta: {
      titleKey: 'menu.TicketDetail',
      layout: 'normal',
      keepAlive: false,
      order: 2,
      show: false,
      roles: ['ADMIN', 'SUPPORT'],
      parentKey: 'Tickets',
      group: routeGroups.Tickets,
    },
  },
  {
    name: 'Users',
    path: '/users',
    component: () => import('@/views/users/index.vue'),
    meta: {
      titleKey: 'menu.Users',
      layout: 'normal',
      keepAlive: true,
      icon: 'i-fe:user',
      order: 3,
      show: true,
      roles: ['ADMIN'],
    },
  },
  {
    name: 'Audit',
    path: '/audit',
    component: () => import('@/views/audit/index.vue'),
    meta: {
      titleKey: 'menu.Audit',
      layout: 'normal',
      keepAlive: true,
      icon: 'i-fe:file-text',
      order: 5,
      show: true,
      roles: ['ADMIN'],
    },
  },
  {
    name: '403',
    path: '/403',
    component: () => import('@/views/error-page/403.vue'),
    meta: {
      titleKey: 'errors.403Title',
      layout: 'empty',
      show: false,
    },
  },
  {
    name: '404',
    path: '/404',
    component: () => import('@/views/error-page/404.vue'),
    meta: {
      titleKey: 'errors.404Title',
      layout: 'empty',
      show: false,
    },
  },
  {
    path: '/:pathMatch(.*)*',
    redirect: '/404',
  },
]
