export const frontendPermissionTree = [
  {
    code: 'Kyc',
    name: 'KYC 審核',
    type: 'MENU',
    icon: 'i-fe:shield',
    order: 1,
    show: true,
    path: '/kyc',
    redirect: '/kyc/pending',
    roles: ['ADMIN', 'AUDITOR'],
    children: [
      {
        code: 'KycPending',
        name: '待審核列表',
        type: 'MENU',
        path: '/kyc/pending',
        component: '/src/views/kyc/pending/index.vue',
        layout: 'normal',
        keepAlive: true,
        show: true,
        order: 1,
        roles: ['ADMIN', 'AUDITOR'],
      },
      {
        code: 'KycAppeals',
        name: '申訴列表',
        type: 'MENU',
        path: '/kyc/appeals',
        component: '/src/views/kyc/appeals/index.vue',
        layout: 'normal',
        keepAlive: true,
        show: true,
        order: 2,
        roles: ['ADMIN', 'AUDITOR'],
      },
      {
        code: 'KycDetail',
        name: '審核詳情',
        type: 'MENU',
        path: '/kyc/detail/:id',
        component: '/src/views/kyc/detail/index.vue',
        layout: 'normal',
        keepAlive: false,
        show: false,
        order: 3,
        roles: ['ADMIN', 'AUDITOR'],
      },
    ],
  },
  {
    code: 'Tickets',
    name: '客服工單',
    type: 'MENU',
    icon: 'i-fe:message-square',
    order: 2,
    show: true,
    path: '/tickets',
    redirect: '/tickets',
    roles: ['ADMIN', 'SUPPORT'],
    children: [
      {
        code: 'TicketList',
        name: '工單列表',
        type: 'MENU',
        path: '/tickets',
        component: '/src/views/tickets/index.vue',
        layout: 'normal',
        keepAlive: true,
        show: true,
        order: 1,
        roles: ['ADMIN', 'SUPPORT'],
      },
      {
        code: 'TicketDetail',
        name: '工單詳情',
        type: 'MENU',
        path: '/tickets/:id',
        component: '/src/views/tickets/detail/index.vue',
        layout: 'normal',
        keepAlive: false,
        show: false,
        order: 2,
        roles: ['ADMIN', 'SUPPORT'],
      },
    ],
  },
  {
    code: 'Users',
    name: '用戶管理',
    type: 'MENU',
    icon: 'i-fe:user',
    order: 3,
    show: true,
    path: '/users',
    component: '/src/views/users/index.vue',
    layout: 'normal',
    keepAlive: true,
    roles: ['ADMIN'],
  },
  {
    code: 'Audit',
    name: '審計記錄',
    type: 'MENU',
    icon: 'i-fe:file-text',
    order: 5,
    show: true,
    path: '/audit',
    component: '/src/views/audit/index.vue',
    layout: 'normal',
    keepAlive: true,
    roles: ['ADMIN'],
  },
]
