/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppCard: typeof import('./components/common/AppCard.vue')['default']
    CommonPage: typeof import('./components/common/CommonPage.vue')['default']
    LayoutSetting: typeof import('./components/common/LayoutSetting.vue')['default']
    Modal: typeof import('./components/me/modal/index.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NBackTop: typeof import('naive-ui')['NBackTop']
    NBreadcrumb: typeof import('naive-ui')['NBreadcrumb']
    NBreadcrumbItem: typeof import('naive-ui')['NBreadcrumbItem']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDescriptions: typeof import('naive-ui')['NDescriptions']
    NDescriptionsItem: typeof import('naive-ui')['NDescriptionsItem']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NImage: typeof import('naive-ui')['NImage']
    NInput: typeof import('naive-ui')['NInput']
    NMenu: typeof import('naive-ui')['NMenu']
    NModal: typeof import('naive-ui')['NModal']
    NPagination: typeof import('naive-ui')['NPagination']
    NRadioButton: typeof import('naive-ui')['NRadioButton']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NSelect: typeof import('naive-ui')['NSelect']
    NSkeleton: typeof import('naive-ui')['NSkeleton']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    NTab: typeof import('naive-ui')['NTab']
    NTabs: typeof import('naive-ui')['NTabs']
    NTooltip: typeof import('naive-ui')['NTooltip']
    ResponsiveTable: typeof import('./components/common/ResponsiveTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheFooter: typeof import('./components/common/TheFooter.vue')['default']
    TheLogo: typeof import('./components/common/TheLogo.vue')['default']
    ToggleTheme: typeof import('./components/common/ToggleTheme.vue')['default']
  }
}

// For TSX support
declare global {
  const AppCard: typeof import('./components/common/AppCard.vue')['default']
  const CommonPage: typeof import('./components/common/CommonPage.vue')['default']
  const LayoutSetting: typeof import('./components/common/LayoutSetting.vue')['default']
  const Modal: typeof import('./components/me/modal/index.vue')['default']
  const NAvatar: typeof import('naive-ui')['NAvatar']
  const NBackTop: typeof import('naive-ui')['NBackTop']
  const NBreadcrumb: typeof import('naive-ui')['NBreadcrumb']
  const NBreadcrumbItem: typeof import('naive-ui')['NBreadcrumbItem']
  const NButton: typeof import('naive-ui')['NButton']
  const NCard: typeof import('naive-ui')['NCard']
  const NCheckbox: typeof import('naive-ui')['NCheckbox']
  const NConfigProvider: typeof import('naive-ui')['NConfigProvider']
  const NDataTable: typeof import('naive-ui')['NDataTable']
  const NDescriptions: typeof import('naive-ui')['NDescriptions']
  const NDescriptionsItem: typeof import('naive-ui')['NDescriptionsItem']
  const NDropdown: typeof import('naive-ui')['NDropdown']
  const NEmpty: typeof import('naive-ui')['NEmpty']
  const NForm: typeof import('naive-ui')['NForm']
  const NFormItem: typeof import('naive-ui')['NFormItem']
  const NImage: typeof import('naive-ui')['NImage']
  const NInput: typeof import('naive-ui')['NInput']
  const NMenu: typeof import('naive-ui')['NMenu']
  const NModal: typeof import('naive-ui')['NModal']
  const NPagination: typeof import('naive-ui')['NPagination']
  const NRadioButton: typeof import('naive-ui')['NRadioButton']
  const NRadioGroup: typeof import('naive-ui')['NRadioGroup']
  const NSelect: typeof import('naive-ui')['NSelect']
  const NSkeleton: typeof import('naive-ui')['NSkeleton']
  const NSpace: typeof import('naive-ui')['NSpace']
  const NSpin: typeof import('naive-ui')['NSpin']
  const NTab: typeof import('naive-ui')['NTab']
  const NTabs: typeof import('naive-ui')['NTabs']
  const NTooltip: typeof import('naive-ui')['NTooltip']
  const ResponsiveTable: typeof import('./components/common/ResponsiveTable.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const TheFooter: typeof import('./components/common/TheFooter.vue')['default']
  const TheLogo: typeof import('./components/common/TheLogo.vue')['default']
  const ToggleTheme: typeof import('./components/common/ToggleTheme.vue')['default']
}
